version: '3'
services:
  db:
    image: postgres:11.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:delegated
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
  pgweb:
    build: ./pgweb
    container_name: "pgweb"
    ports:
        - "8081:8081"
    environment:
        - DATABASE_URL=postgres://root:password@postgres:5432/{DBmame}?sslmode=disable
    links:
        - db:db
    restart: always
    depends_on:
        - db